name: Bot Safe Auto
on:
  schedule:
    - cron: '0 8 * * *'  # 9h00 du matin (Analyse de la journée)
    - cron: '0 12 * * *' # 13h00 (Dernière vérification avant les matchs)
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python main.py
