name: Bot Safe Auto
on:
  schedule:
    - cron: '0 8 * * *'  # 9h00 (Heure FR)
  workflow_dispatch:      # Bouton manuel
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: python main.py
