name: Bot Safe Automatique
on:
  schedule:
    - cron: '0 8 * * *'  # Se lance à 9h00 (Heure FR)
  workflow_dispatch:      # Le bouton pour lancer manuellement
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Execution
        run: python main.py
